//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorkBoardProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corkboard
    {
        public int Cid { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public int VisibilityId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Watch { get; set; }
    }
}
