//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorkBoardProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int Lid { get; set; }
        public int UserId { get; set; }
        public int PushpinId { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
